spring:
  profiles:
    active: local
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

# MyBatis配置
mybatis:
  # mapper xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名包
  type-aliases-package: top.zhaizz.entity
  configuration:
    map-underscore-to-camel-case: true  # 下划线自动转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印执行SQL